In [1]:
import torch
!nvidia-smi

Mon Oct 27 11:46:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#**1st exercise**
Create a random tensor with shape (6,6).

In [29]:
torch.cuda.manual_seed(0)
firstor= torch.rand(6,6, device='cuda')
firstor

tensor([[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967],
        [0.4150, 0.8203, 0.2290, 0.9096, 0.1183, 0.0752],
        [0.4092, 0.9601, 0.2093, 0.1940, 0.8909, 0.4387],
        [0.3570, 0.5454, 0.8299, 0.2099, 0.7684, 0.4290],
        [0.2117, 0.6606, 0.1654, 0.4250, 0.9927, 0.6964],
        [0.2472, 0.7028, 0.7494, 0.9303, 0.0494, 0.0750]], device='cuda:0')

#2nd exercise
Multiply the tensor from exercise 1 with a new random tensor of shape (2, 6). You may need to transpose the second tensor in order to perform the multiplication correctly

In [28]:
torch.cuda.manual_seed(0)
secondor = torch.rand(2,6,device ="cuda").T
secondor
lastor = torch.matmul(firstor,secondor) # dot product
lastor

tensor([[2.8400, 1.6221],
        [1.6221, 1.7445],
        [2.0391, 1.3201],
        [1.7109, 1.0997],
        [2.3232, 1.2240],
        [1.4615, 1.7084]], device='cuda:0')

##Find the maximum and minimum values of the output of 2.

In [33]:
max_value = torch.max(lastor)
min_value = torch.min(lastor)
maxindex = torch.argmax(lastor)
minindex = torch.argmin(lastor)

print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")
maxindex, minindex

Maximum value: 2.839986801147461
Minimum value: 1.0997406244277954


(tensor(0, device='cuda:0'), tensor(7, device='cuda:0'))

### Create a random tensor with a shape of (1, 1, 1, 6), and then generate a new tensor by removing all singleton dimensions, resulting in a tensor of shape (6).

In [36]:
lastQuest = torch.rand(1,1,1,10)
lastQuest=lastQuest.squeeze()
lastQuest=lastQuest.squeeze()
lastQuest=lastQuest.squeeze()
lastQuest

tensor([0.3986, 0.7742, 0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037,
        0.4018])