In [1]:
#THIS FXN THING TOOK 6 HOURS TO MAKE OMG
#testing collab if everything works
#don't forget to change the runtime type to GPU.
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
!nvidia-smi

2.8.0+cu126
Mon Oct 27 11:11:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------

Intro to Tensors

creating tensors

In [2]:
#scalar
scalar = torch.tensor(8)
scalar


tensor(8)

In [3]:
#ndim shows that how many dimentions is there.
scalar.ndim

0

In [4]:
#get tensor back as a python int
print(scalar.item())

8


In [5]:
#Vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[8,9]])
MATRIX.ndim

2

In [9]:
MATRIX[0]


tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 9, 10, 11]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

##Random Tensors
### Why random tensors because the way the ml work is like this:


```
# Random numbers ->
      while True:
         look at data
         update random numbers -> look at data
```



In [14]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1853, 0.5933, 0.9288, 0.3585],
         [0.1621, 0.7000, 0.0932, 0.6512],
         [0.2200, 0.6617, 0.9013, 0.7401]]])

In [15]:
#random image size tensor
#224x224 red green blue picture
random_img_size_tensor = torch.rand(size=(3,224,224))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [16]:
#zeroes and ones
zerose = torch.zeros(size=(1,3,4))
ones = torch.ones(size=(2,3,4))
print(zerose)
print(ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [17]:
#default datatype is float. take a look here
random_tensor.dtype, ones.dtype

(torch.float32, torch.float32)

### Creating the range of tensors and tensors-like


In [18]:
#use torch.arange()
thirteen_toHunderd = torch.arange(0,100,13)
#Starting index and ending index, and step
#thirteen_toHunderd.ndim

In [19]:
#Creating tensors-like
#A tensor-like is kinda a numpy array or a normal array and the "like" functions turns them into a tensor.
someZeroes =  torch.zeros_like(thirteen_toHunderd)
someZeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

####Tensor datatypes are one of the 3 big errors w pytorch and deep learning
1) Tensors not right datatype(thistopic)
2) Tensors not right shape.
3) Tensors not on the right device.

In [20]:
#Float 32 Tensor (Default data type)
float32Tensor = torch.rand(1,10)
float32Tensor.dtype


torch.float32

In [21]:
#Float 16 Tensor (I'm showing how to change datatype)
#Use dtype to change datatype of it while making the function.
#dtype, device and requires_grad are VERY very important.
float16Tensor = torch.rand([1,10], dtype=torch.float16, #   Datatype
                           device="cpu", # what device is this tensor going to be on
                 requires_grad=False) # whether or not to track gradients with this tensors operations
float16Tensor.dtype

torch.float16

In [22]:
#Changing the type of a Tensor
float32Tensor = float32Tensor.type(torch.float64)
float32Tensor.dtype

torch.float64

In [23]:
#multiplying the tensors
float16Tensor*float32Tensor #changed datatype to the bigger one
#It won't always result without error.

tensor([[0.1125, 0.4809, 0.1560, 0.4934, 0.6474, 0.5460, 0.0773, 0.3966, 0.1386,
         0.0565]], dtype=torch.float64)

###Getting information from the tensors
1) Tensors not right datatype<br>
- To get datatype use:

```
tensor.dtype
```


2) Tensors not right shape. <br>
- To get the shape use:
```
tensor.shape
```
3) Tensors not on the right device.
- To get the device knowledge use:
```
tensor.device
```

In [24]:
#Create a tensor
someThing = torch.rand([1,10], dtype=torch.float16, device="cpu")

In [25]:
#Getting info about the tensor
#That's how you can see normally on your general ide
print(someThing)
print(f"Datatype of the tensor:{someThing.dtype}")
print(f"Device of the tensor:{someThing.device}")
print(f"Shape of the tensor: {someThing.shape}")

tensor([[0.2529, 0.0474, 0.6558, 0.0278, 0.8828, 0.1675, 0.1201, 0.2368, 0.2529,
         0.6558]], dtype=torch.float16)
Datatype of the tensor:torch.float16
Device of the tensor:cpu
Shape of the tensor: torch.Size([1, 10])


###Manipulating Tensors (Tensor operations)
####Tensor operations include:
- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix Multiplication

In [26]:
maniTensor = torch.rand([1,10], dtype=torch.float16)
#adding
maniTensor+=10
print(maniTensor)
#multiplying
maniTensor*=10
print(maniTensor)
#subtracting
maniTensor-=31
print (maniTensor)
#dividing
maniTensor/=5
print(maniTensor)

tensor([[10.3750, 10.2031, 10.2344, 10.2266, 10.7422, 10.4844, 10.3672, 10.4375,
         10.4219, 10.3594]], dtype=torch.float16)
tensor([[103.7500, 102.0000, 102.3750, 102.2500, 107.4375, 104.8750, 103.6875,
         104.3750, 104.2500, 103.6250]], dtype=torch.float16)
tensor([[72.7500, 71.0000, 71.3750, 71.2500, 76.4375, 73.8750, 72.6875, 73.3750,
         73.2500, 72.6250]], dtype=torch.float16)
tensor([[14.5469, 14.2031, 14.2734, 14.2500, 15.2891, 14.7734, 14.5391, 14.6719,
         14.6484, 14.5234]], dtype=torch.float16)


In [27]:
#you can use pytorch's in-built functions for addition multplying etc. but doing this way easier.
#If normal python syntax doesn't work, you can try pytorch's documentation

### Matrix multiplication
2 main ways of multiplication in neural networks and deep learning:
1. Element-wise multiplication (Normal multiplication that we use in our daily life)
2. Matrix Multiplication(dot product)

In [28]:
###Element wise multiplication
print (f"{maniTensor} * {maniTensor}")
print(f"equals to {maniTensor*maniTensor}")

tensor([[14.5469, 14.2031, 14.2734, 14.2500, 15.2891, 14.7734, 14.5391, 14.6719,
         14.6484, 14.5234]], dtype=torch.float16) * tensor([[14.5469, 14.2031, 14.2734, 14.2500, 15.2891, 14.7734, 14.5391, 14.6719,
         14.6484, 14.5234]], dtype=torch.float16)
equals to tensor([[211.6250, 201.7500, 203.7500, 203.0000, 233.7500, 218.2500, 211.3750,
         215.2500, 214.6250, 210.8750]], dtype=torch.float16)


In [29]:
#making a new tensor to be able to matrix-multiply it by maniTensor.
maniTensor = maniTensor.type(torch.float16)
mamiTensor = torch.rand(10,1, dtype=torch.float16)

In [30]:
###Dot Product
#we use torch.matmul(tensor,tensor) in here.
torch.matmul(maniTensor, mamiTensor)

tensor([[63.4375]], dtype=torch.float16)

In [31]:
###Transposing a Matrix (for example making a 3x2 matrix 2x3)
maniTensor = maniTensor.T
maniTensor
mamiTensor = mamiTensor.T
mamiTensor
#See how it changes
torch.matmul(maniTensor, mamiTensor)

tensor([[ 1.3848,  1.6475,  2.0957,  7.7852,  9.3359,  9.1953,  4.0469,  2.1660,
         13.3359, 11.9688],
        [ 1.3525,  1.6094,  2.0449,  7.6016,  9.1094,  8.9844,  3.9531,  2.1152,
         13.0156, 11.6875],
        [ 1.3594,  1.6172,  2.0566,  7.6367,  9.1562,  9.0234,  3.9727,  2.1250,
         13.0781, 11.7422],
        [ 1.3564,  1.6143,  2.0527,  7.6250,  9.1406,  9.0078,  3.9668,  2.1230,
         13.0625, 11.7266],
        [ 1.4561,  1.7324,  2.2031,  8.1797,  9.8125,  9.6641,  4.2539,  2.2773,
         14.0156, 12.5781],
        [ 1.4062,  1.6738,  2.1289,  7.9062,  9.4766,  9.3438,  4.1133,  2.1992,
         13.5391, 12.1562],
        [ 1.3848,  1.6475,  2.0938,  7.7812,  9.3281,  9.1953,  4.0469,  2.1660,
         13.3281, 11.9609],
        [ 1.3975,  1.6621,  2.1133,  7.8516,  9.4141,  9.2812,  4.0820,  2.1855,
         13.4453, 12.0703],
        [ 1.3945,  1.6592,  2.1094,  7.8398,  9.3984,  9.2656,  4.0781,  2.1816,
         13.4219, 12.0547],
        [ 1.3828,  

###Finding the min, max , mean , sum etc(tensor aggregation)

In [32]:
#create a new tensor
tenseur = torch.arange(0,100,10, dtype=torch.float16)
tenseur

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [33]:
#find the min and max, mean and sum
torch.min(tenseur), torch.max(tenseur), torch.mean(tenseur), torch.sum(tenseur)

(tensor(0., dtype=torch.float16),
 tensor(90., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(450., dtype=torch.float16))

In [34]:
#Finding the positional value of min and max
tenseur.argmin(), tenseur.argmax()
tenseur[tenseur.argmax()]

tensor(90., dtype=torch.float16)

###Reshaping, stacking squeezing und unsqueezing the tensors

- Reshaping - reshaps an input tensor to a defined shape
* View - Return a view of an input of an unput tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensirs on top if each other(vstack) or side by side(hstack)
* squeeze - removes all `1` dimensions from a tensor
* unsqueeze - add a `1` dimension to a target tensor
- permute - return a view of the input with dimensions permuted (swapped) in a certain way



In [35]:
#Making a new tensor
oneTen = torch.arange(1,10)
oneTen, oneTen.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [36]:
#Adding an extra dimension
oneTenRe = oneTen.reshape(3,3)
#it should be suitable for size you have we have 9 elements in here for example.
oneTenRe

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [37]:
#Changing the view
#View is keeped in the same memory as original so changing the viewed thing
#would change the original one. lets see!
fakeTen = oneTen.view(1,9)
fakeTen
fakeTen[:,0] = 99
fakeTen, oneTen #see?

(tensor([[99,  2,  3,  4,  5,  6,  7,  8,  9]]),
 tensor([99,  2,  3,  4,  5,  6,  7,  8,  9]))

In [38]:
# Stack tensors on top of each other
# h stack is horisontal so it's like a single stack added to each other
# but v stack is vertical so you got kinda the same results as normal stack in dimension 1
fakeTen_stacked = torch.stack([fakeTen,fakeTen,fakeTen,fakeTen], dim=1)
fakeTen_stacked

tensor([[[99,  2,  3,  4,  5,  6,  7,  8,  9],
         [99,  2,  3,  4,  5,  6,  7,  8,  9],
         [99,  2,  3,  4,  5,  6,  7,  8,  9],
         [99,  2,  3,  4,  5,  6,  7,  8,  9]]])

In [39]:
#torch.squeeze() - removes all single dimensions from a target tensor
# all ones in size in removed
# torch.squeeze() reverses the squeeze method
#dim=0 is default
fakeTen.squeeze().shape, fakeTen.shape, fakeTen.unsqueeze(dim=0)

(torch.Size([9]),
 torch.Size([1, 9]),
 tensor([[[99,  2,  3,  4,  5,  6,  7,  8,  9]]]))

In [40]:
#torch.permute() changes the order of the tensor here is how you can do it:
showTensor = torch.randn(2,3,5);
showTensor.shape, torch.permute(showTensor,(1,2,0)).size()
# it changed the shape of the function

(torch.Size([2, 3, 5]), torch.Size([3, 5, 2]))

###Indexing (selecting data from tensors)
#### INdexing with pytorch is similar to indexing with NumPy

In [41]:
#Creating a tensor:
inTensor = torch. arange(1,10).reshape(1,3,3)
inTensor, inTensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [42]:
# Let's index our new Tensor!
#You can use : to select from or until a dimention
#:1 until 1st index, 1: from the 1st index
inTensor[0,1:,2]

tensor([6, 9])

# PyTorch <3 NumPy

In [43]:
## NumPy Array to PyTorch Tensor --> torch.from_numpy(ndarray)
## PyTorch Tensor To NumPy Array --> torch.Tensor.numpy()
array = np.arange(1.0,10.0)
tenumpy= torch.from_numpy(array).type(torch.float16)
tenumpy
#we've changed it from a numpy array to pytorch tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [44]:
#now we're going to change this back to a numpy array
#KEEP IN MIND THAT PYTORCH DEFAULT DATA TYPE IS FLOAT32 AND NUMPY'S IS FLOAT64
Narray = torch.Tensor.numpy(tenumpy)
Narray

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

## Reproductbility(Trying to take random out of random)
###In short, how a neural network learns:
####

```
Start with random numbers -> tensor operations -> update random numbers to try
and make their representations of the data better -> again > again > and AGAIN
```
TO reduce the randomness in nerural networks and PyTorch comes <br>
the concept of a ***random seed***.

Essentially what random seed does is "how random's algorithm works"

In [45]:
#without a seed it probably is wrong.
rand_tens = torch.rand(3,4)
rant_dens = torch.rand(3,4)
print(rand_tens)
print(rant_dens)
print(rand_tens==rant_dens)

tensor([[0.8028, 0.7171, 0.2274, 0.6677],
        [0.7355, 0.2911, 0.5705, 0.7925],
        [0.6864, 0.3851, 0.2219, 0.5689]])
tensor([[0.4017, 0.2310, 0.4198, 0.5287],
        [0.3201, 0.3266, 0.0294, 0.7387],
        [0.0019, 0.6165, 0.0788, 0.0606]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [46]:
#reproducible tensors with random seeds
#set the random seed
#I'm setting it as 92 because that's my nickname!
torch.manual_seed(92)
rany_tens = torch.rand(3,4)
torch.manual_seed(92)
#You should use everytime you want to call rand protocol
ranb_dens = torch.rand(3,4)
print(rany_tens)
print(ranb_dens)
print(rany_tens==ranb_dens)
#ZORT

tensor([[0.7854, 0.9900, 0.8769, 0.2035],
        [0.7304, 0.0142, 0.5906, 0.0460],
        [0.0906, 0.7427, 0.2300, 0.0746]])
tensor([[0.7854, 0.9900, 0.8769, 0.2035],
        [0.7304, 0.0142, 0.5906, 0.0460],
        [0.0906, 0.7427, 0.2300, 0.0746]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###Running Tensors and pytorch objects on the GPUs(AND MAKE FASTER COMPUTATIONS)


### Getting the GPU
1. using here
2. using your own hardware
3. cloud computing(aws,azure etc.)

For 2,3 -> PyTorch + GPU drivers(cuda) (look to pytorch's own documentation)

In [48]:
##Check GPU access with PyTorch
torch.cuda.is_available()

True

In [50]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [51]:
# count the number of devices
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [55]:
tenswoof = torch.tensor([1,2,3], device="cuda")
tenswoof.device
#index 0 means you're in the first index of gpus
#cuda means gpu

device(type='cuda', index=0)

###Moving Tensors back into The CPU

In [58]:
#If tensors is on GPU, you can't transform them ito to numpy
#use tensor_name.cpu() method to convert it back to cpu from gpu.
tenswoof.cpu().numpy()


array([1, 2, 3])